config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'

 
  get '/audio', to: 'songs#showAudio'
  get  '/about',  to: 'static_pages#about'
  get  '/help',   to: 'static_pages#help' 
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  post '/add', to: 'songs#add'
  get '/search', to: 'search#showsearch'
  post '/review', to: 'users#review' 
  
  resources :users
  resources :audios do
    member do
      put "like", to: "songs#upvote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audio.rb
class Audio < ApplicationRecord
  acts_as_votable
  before_save {self.path = path.downcase}
  validates :path, presence: true 
end

app/models/editor.rb
class Editor < ApplicationRecord

	validates :song, presence: true, uniqueness: true 
end

app/models/genre.rb
class Genre < ApplicationRecord
	validates :name,presence: true, uniqueness: true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :song, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/singer.rb
class Singer < ApplicationRecord
	validates :name,presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }

  has_many :playlists, dependent: :destroy

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
  include SessionsHelper


  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

	def showsearch
		if !current_user.nil?
         @search = params[:search].downcase
		render layout: 'alt'
  else

    flash[:notice] = "Sign In Please"
    redirect_to root_path 
  end
		
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
       log_in user
      redirect_to user

    else
      # Create an error message.
            flash.now[:danger] = 'Invalid email/password combination' 
            render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def showAudio

    if !current_user.nil?
    @str =  params[:id]
    @u = params[:uid]
    @count = Audio.count
  	render layout: 'alt'
  else 
    flash[:notice] = "Sign In Please"
    redirect_to root_path 
  end
  end


  def add
    @s1 = params[:song]
    @s2 = params[:path]
    @s3 = params[:id]
    Playlist.create(song: @s1, path: @s2,user_id: @s3)
    
  end



  def upvote
    @link=Audio.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def review
    
    Review.create(post: params[:review])
    
    
  end

  def show
    if !current_user.nil?
           @user = User.find(params[:id])
           render layout: 'alt'
  else

    flash[:notice] = "Sign In Please"
    redirect_to root_path 
  end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Pandora"
      redirect_to @user
    else
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  
  end

   def update
    @user = User.find(params[:id])
    
    if @user.update_attributes(user_params)
      redirect_to @user
      # Handle a successful update.
    else
      render 'edit'
    end
  end


   private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title='')
		base_title="Pulse"
		 if page_title.empty?
        base_title
    		else
    			    "#{page_title} | #{base_title}"
   end
    end
end

app/helpers/search_helper.rb
module SearchHelper
	def full_title(page_title='')
		base_title="Pulse"
		 if page_title.empty?
        base_title
    		else
    			    "#{page_title} | #{base_title}"
   end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  def full_title(page_title='')
    base_title="Pulse"
     if page_title.empty?
        base_title
        else
              "#{page_title} | #{base_title}"
            end
    end
  
end

app/helpers/songs_helper.rb
module SongsHelper
	def full_title(page_title='')
		base_title="Pulse"
		 if page_title.empty?
        base_title
    		else"#{page_title} | #{base_title}"
   end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def full_title(page_title='')
		base_title="Pulse"
		 if page_title.empty?
        base_title
    		else
    			    "#{page_title} | #{base_title}"
   end
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  def full_title(page_title='')
		base_title="Pulse"
		 if page_title.empty?
        base_title
    		else
    			    "#{page_title} | #{base_title}"
   end
    end
  
end

app/views/layouts/_footer.html.erb
<div class="container" style="float:bottom">
  <div class="footer">
 
    <div class="col-lg-12">
      <div class="col-md-8">
  
<font face="WildWest" color="#02C54C" size="5">
    <a>Project</a> : <a class="btn btn-social-icon btn-github" href="https://github.com/aman935/adp">
      <i class="fa fa-github fa-3x"></i> 
<a>Github Repo : ADP</a>
  </a>
    &nbsp; &nbsp;   | &nbsp; &nbsp;  <a href="https://github.com/aman935/adp#readme">About</a>
  </a>
</font>

      </div>
      
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="top">

<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
  <%= image_tag("logo.png",id: "log") %>
    <%= link_to "Pulse", '/', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to "About", "https://github.com/aman935/adp#readme", id: "navA" %></li>
         <% if logged_in? %>
         
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span>Account</span><b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
        <li><%= link_to "Profile", current_user%></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li>
        <%= link_to "Log out", logout_path, method: "delete"%>
        </li>
        </ul>
        </li>
        <% else %>
        <li><%= link_to "Log In",   login_path, id: "navA" %></li>
        <li><%= link_to "Sign Up", signup_path, id: "navA" %></li>
        <% end %>

        
        
      </ul>
    </nav>
  </div>

</header>
  </div>

app/views/layouts/_header1.html.erb
</head> 


         <!-- /w3layouts-agile -->
 <body class="sticky-header left-side-collapsed"  onload="initMap()">
    <section>
      <!-- left side start-->
        <div class="left-side sticky-left-side">

            <!--logo and iconic logo start-->
            
            <div class="logo-icon text-center">
                <%= link_to "P", '/' %>
            </div>
     
            <div class="left-side-inner">

                
                    <ul class="nav nav-pills nav-stacked custom-nav">
                        <button id="myBtn" onclick="showreview()"><%= image_tag("review.png")%></button>                   
                       
                           
                    </ul>
                
            </div>
        </div>

        <div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="modal-content">
    <span class="close">x</span>
    
                             <%= form_tag(review_path, :method => "post", id: "review-form") do %>
                             <%= text_area_tag :review, params[:review],id: "rbar",placeholder: "Your review is precious"%>
                             <%= submit_tag "Submit", :name => nil, class: "btn btn-primary btn-sm",id: "sbutton"%>
                             <% end %>

    
  </div>

</div>



           
               
                        
                                
                                <div class="clearfix"> </div>
                            </div>
                        
                        <div class="col-md-7 app-image">
                           
                        </div>
                        <div class="clearfix"></div>
                    </div>
                
                                    <div class="clearfix"></div>                                
                        
        <div class="main-content">
            <!-- header-starts -->
            <div class="header-section">
       
                <div class="menu-right">
                    <div class="profile_details">       
                          <div class="col-md-4 serch-part">
                          
                             <div class="search" style="margin-top: 12px">
                             <%= form_tag(search_path, :method => "get", id: "search-form") do %>
                             <%= text_field_tag :search, params[:search], placeholder: "Search genre name artist",id: "sbar"%>
                             <%= submit_tag "Search", :name => nil, class: "btn btn-primary btn-sm",id: "sbutton"%>
                             <% end %>
                                </div>

                            </div>
                              <!-- search-scripts -->
                                    <script src="js/classie.js"></script>
                                    <script src="js/uisearch.js"></script>
                                        <script>
                                            new UISearch( document.getElementById( 'sb-search' ) );
                                        </script>
                                    <!-- //search-scripts -->
                                             <!---->
                                              <div class="col-md-4 player">
                                                    <div class="audio-player">
                                                    <audio id="audio-player"  controls="controls">
                                                    <source id="oggSource" this.src="source.src" type="audio/ogg"></source>
                                                    <source id="mp3Source" src="" type="audio/mp3"></source>
                                                        </div>

                                                                                 
                                                
                                                <script type="text/javascript">
                                                    $(function(){
                                                      $('#audio-player').mediaelementplayer({
                                                        alwaysShowControls: true,
                                                        features: ['playpause','progress','volume'],
                                                        audioVolume: 'horizontal',
                                                        iPadUseNativeControls: true,
                                                        iPhoneUseNativeControls: true,
                                                        AndroidUseNativeControls: true
                                                    });
                                                 });
                                                </script>
                                                <!--audio-->
                                                    <link rel="stylesheet" type="text/css" media="all" href="css/audio.css">
                                                    <script type="text/javascript" src="js/mediaelement-and-player.min.js"></script>
                                                    <!---->


                                                <!--//-->
                                                <ul class="next-top">
                                                    <li><a class="ar" href="#"> <img src="/assets/arrow.png" alt=""/></a></li>
                                                    <li><a class="ar2" href="#"><img src="/assets/arrow2.png" alt=""/></i></a></li>
                                                        
                                             </ul>  
                                            </div>
                                            <div class="col-md-4 login-pop">
                                                <div id="loginpop">  <%= link_to'<i class="fa fa-sign-out fa-2x"></i><font size="5">Logout</font>'.html_safe , logout_path , method: "delete",id: "lo" %>
                                                        <div id="loginBox">  
                                           
                                                    </div>
                                                </div>
                                                <div style="float: right;">
        <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span id="lo">	    
	  <i class="fa fa-user fa-2x" aria-hidden="true"></i><font size="5"> Account</font></span>
        </a>
        <ul class="dropdown-menu">
        <li><%= link_to '<i class="fa fa-users fa" aria-hidden="true"></i>  Profile'.html_safe, current_user,id: "la"%></li>
        <li><%= link_to '<i class="fa fa-cog fa" aria-hidden="true"></i><font size="4">  Settings</font>'.html_safe, edit_user_path(current_user) %></li>
        <li class="divider"></li>
        </ul>
        </div>


                                            </div>
        
        


                                        <div class="clearfix"> </div>

                                </div>

                            
                        </div>
                    <div class="clearfix"></div>
                </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/alt.html.erb
<!DOCTYPE html>

<html>
<div class="app">
  <head>
    
   <title><%=full_title(yield(:title))%></title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body style="margin: 0;">

   
   <%= render 'layouts/header1' %>

    
      <%= yield %>

        
     
   <%= render 'layouts/footer' %>
     
  </body>
   </div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<div class="app">
  <head>
   <title><%=full_title(yield(:title))%></title>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body style="padding-top:30px;
  margin:0;
  background: url(/assets/a.jpg)no-repeat; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  -ms-background-size: cover;
  background-size: cover;
  font-family: 'Roboto Condensed', sans-serif;
  background-attachment: fixed; ">

    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <br>
      <%= yield %>
      <%= render 'layouts/footer' %>
      

    </div>
   
  </body>
   </div>
</html>

app/views/search/showsearch.html.erb
<div class="audio-main w3ls">
	
	<div class="audio-record-list">
	<div class="profile">
			 <div class="profile-top wthree">
				 <div class="pic-sec">
					 <div class="pic">
						 <img src="/assets/searchicon.jpg" alt="<%=@search%>"/>
					 </div>
					 <div class="pic_info">
						 <h2><%=@search.upcase%></h2>
						 
					 </div>
					 <div class="clear"></div>
				 </div>
				 			 </div>
		 </div>
					
		</div>

       

		<div class="jp-playlist2">

	<div class="jp-playlist2">
	  <style>
	    table.myTable { 

	    border-collapse: separate;
	    border-spacing: 10px;
	    background-color:#EFEFEF;
	    border:0;
	    }
	  </style>
	    <table class="myTable" 	    width="100%">
	 
	  
		<ul style="display: block;">
         <% (1..Audio.count).each do |i| %>
         <% if Audio.find(i).artist.downcase  == @search or Audio.find(i).genre.downcase  == @search or Audio.find(i).name.downcase  == @search  %>
         
		<tr>
                                                    <ul style="display: block;">
                                                    <li><div><td><a  class="jp-playlist-item-remove" style="display: none;">×</a><a  class="jp-playlist-item" onclick="updateSource(this)" data-value="<%=Audio.find(i).path%>" tabindex="0"><span id="songName"><%= Audio.find(i).name%></span></a></td>
<td>
                                                    <%= link_to '<font size="4">Add to playlist</font> <i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i>'.html_safe,add_path(:song => Audio.find(i).name,:path => Audio.find(i).path,:id => @u),:method => :post %> </td>
	  <td>
		    <%= link_to  like_audio_path(Audio.find(i)), method: :put do %>
		  <font size="4">  Upvote </font><i class="fa fa-thumbs-up fa-2x" aria-hidden="true"></i>
	       <%= Audio.find(i).get_upvotes.size %>
		  </td>
		       <% end %>
                                                    </div>

                                                    </li>
						    </tr>



           <% else %>                                     
             
          <% end %>

          <% end %>
	  </ul>
          </table>
          </div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/songs/showAudio.html.erb
<% provide(:title, "Songs") %>
<div class="audio-main w3ls">
	
	<div class="audio-record-list">
	<div class="profile">
			 <div class="profile-top wthree">
				 <div class="pic-sec">
					 <div class="pic">
						 <img src="/assets/<%=@str%>.jpg" alt="<%=@str%>"/>
					 </div>
					 <div class="pic_info">
						 <h2><%=@str%></h2>
						 
					 </div>
					 <div class="clear"></div>
				 </div>
				 			 </div>
		 </div>
					
		</div>

       

		<div class="jp-playlist2">
		<ul style="display: block;">
         <% (1..@count).each do |i| %>
         <% if Audio.find(i).artist  == @str or Audio.find(i).genre  == @str  %>
         

                                                    <ul style="display: block;">
                                                    <li><div><a  class="jp-playlist-item-remove" style="display: none;">×</a><a  class="jp-playlist-item" onclick="updateSource(this)" data-value="<%=Audio.find(i).path%>" tabindex="0"><span id="songName"><%= Audio.find(i).name%></span></a>

                                                    <%= link_to "Add to playlist",add_path(:song => Audio.find(i).name,:path => Audio.find(i).path,:id => @u),:method => :post %>
						    <%= link_to  like_audio_path(Audio.find(i)), method: :put do %>
  Upvote
						    <%= Audio.find(i).get_upvotes.size %>
<% end %>
                                                    </div>

                                                    </li>




           <% else %>                                     
             
          <% end %>

          <% end %>
          
          


         
          </ul>
        </div>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>


<!DOCTYPE HTML>
<html>
<body>
<div class="about">

<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>
</div>
</body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="help">
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
</div>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
<span style="color: white">
<% if flash[:notice] %>
    <div class="notice"><h1><%= flash[:notice] %></h1></div>
  <% end %>
</span>
<div class="home">

<head>
</head>


  <!-- Theme Made By www.w3schools.com - No Copyright -->


</div>

</body>
</html>

app/views/users/edit.html.erb
<% provide(:title, "Home") %>

<br/><br/><br/><br/><br/><br/><br/><br/><br/>


<style type="text/css">
#update{
  font-size: 40px;
  text-align: center;
}
  
</style>

<div class="row">

  <div class="col-md-6 col-md-offset-3">
     <span id="update"><h1>Update your profile</h1></span>
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>

    <% end %>

    
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<body>

<div class="new">



 <div class="login agile">
    <div class="w3agile-border">
    
      <div class="login-main login-agileits"> 
        <h1>SignUp</h1> 
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>
</div>
</div>
</body>